#!/usr/bin/env python

import tempfile
import os
import shutil

template_path = "./Templates/GameEpisode"
game_episodes_path = "./Applications/Game/Game/Sources/Game/Scene/Episodes"

episode_name = "Test"
episode_key = "___EPISODE___"

with tempfile.TemporaryDirectory() as working_dir:
    shutil.copytree(template_path, working_dir, dirs_exist_ok=True)

    for root, dirs, files in os.walk(working_dir, topdown=False):
        dirs = [d for d in dirs if not d.startswith(".")]
        files = [f for f in files if not f.startswith(".")]

        for file in files:
            file_path = root + "/" + file
            with open(file_path, "r") as file_desc:
                filedata = file_desc.read()
            filedata = filedata.replace(episode_key, episode_name)
            with open(file_path, "w") as file_desc:
                file_desc.write(filedata)

        for item in files + dirs:
            new_item = item.replace(episode_key, episode_name)
            if item != new_item:
                os.replace(root + "/" + item, root + "/" + new_item)

    shutil.copytree(working_dir, game_episodes_path, dirs_exist_ok=True)